# NanoMQ Configuration 0.18.0

# #============================================================
# # NanoMQ Broker
# #============================================================

mqtt {
    property_size = 32
    max_packet_size = 256MB
    max_mqueue_len = 2048
    retry_interval = 10s
    keepalive_multiplier = 1.25
    
    # Three of below, unsupported now
    max_inflight_window = 2048
    max_awaiting_rel = 10s
    await_rel_timeout = 10s
}

listeners.tcp {
    bind = "0.0.0.0:1883"
}

# listeners.ssl {
# 	bind = "0.0.0.0:8883"
# 	keyfile = "/etc/certs/key.pem"
# 	certfile = "/etc/certs/cert.pem"
# 	cacertfile = "/etc/certs/cacert.pem"
# 	verify_peer = false
# 	fail_if_no_peer_cert = false
# }

listeners.ws {
    bind = "0.0.0.0:8083/mqtt"
}

log {
    to = [file, console]
    level = warn
    dir = "/data/broker"
    file = "nanomq.log"
    rotation {
        size = 10MB
        count = 5
    }
}

auth {
    allow_anonymous = true
    no_match = allow
    deny_action = ignore
    
    cache = {
        max_size = 32
        ttl = 1m
    }
    
    # password = {include "/etc/nanomq_pwd.conf"}
    # acl = {include "/etc/nanomq_acl.conf"}
}

# Tested the below configuration but it did not work at the time

# bridges.mqtt.name {
# 	server = "broker.waraps.org"
# 	proto_ver = 4
# 	clean_start = true
# 	keepalive = 60s

#     # TLS settings
#     tls.enable = true
#     tls.verify_peer = false  # Disable certificate verification

#     # Authentication settings
#     username = "your_username"
#     password = "your_password"

# 	# forwards = [
# 	# 	{
# 	# 		remote_topic = "fwd/topic1"
# 	# 		local_topic = "topic1"
# 	# 		qos = 1
# 	# 	},
# 	# 	{
# 	# 		remote_topic = "fwd/topic2"
# 	# 		local_topic = "topic2"
# 	# 		qos = 2
# 	# 	}
# 	# ]
# 	subscription = [
# 		{
# 			remote_topic = "waraps/general/generic/real/c2/target/positions"
# 			local_topic = "waraps/general/generic/real/c2/target/positions"
# 			qos = 1
# 		},
# 		{
# 			remote_topic = "waraps/unit/air/real/+/sensor/position"
# 			local_topic = "waraps/unit/air/real/+/sensor/position"
# 			qos = 2
# 		}
# 	]
# 	max_parallel_processes = 2 
# 	max_send_queue_len = 1024
# 	max_recv_queue_len = 1024
# }